# Generated by Django 2.2.7 on 2019-11-16 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191115_1822'),
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The task name for the to-do', max_length=200)),
                ('is_done', models.BooleanField(default=False, help_text='This task is done or not')),
                ('due_date', models.DateTimeField()),
                ('bucket', models.ForeignKey(help_text='The bucket id associated with this task', on_delete=django.db.models.deletion.CASCADE, to='to_do.Bucket')),
                ('user', models.ForeignKey(help_text='The user id who posted this task', on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'task',
                'ordering': ['due_date'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
